package com.vinodh.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "EMPLOYEE", schema = "VINODH")
@Data
@NoArgsConstructor
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "EMP_ID", unique = true, nullable = false)
	@GeneratedValue
	private Integer empId;
	@Column(name = "EMP_NAME", nullable = false, length = 111)
	private String empName;
	@Column(name = "EMP_PHONE", nullable = false, precision = 22, scale = 0)
	private Integer empPhone;
	@Column(name = "EMP_SALARY", nullable = false, precision = 22, scale = 0)
	private Integer empSalary;
	@Temporal(TemporalType.DATE)
	@Column(name = "EMP_DOB", nullable = false, length = 7)
	private Date empDob;
	@Column(name = "EMP_EMAIL", nullable = false, length = 64)
	private String empEmail;

}
