SET DATABASE SQL SYNTAX ORA TRUE;
CREATE SCHEMA VINODH
	CREATE TABLE COUNTRIES_LIST (
		COUNTRY_ID		INT NOT NULL,
		COUNTRY_NAME	VARCHAR(100) NOT NULL,
		COUNTRY_CODE	VARCHAR(100) NOT NULL
	)
	CREATE TABLE INDIAN_STATES (
 		STATE_ID INT,
   		STATE_NAME VARCHAR2(50) NOT NULL
    )
    CREATE TABLE EMPLOYEE (
 		EMP_ID INT,
   		EMP_NAME VARCHAR2(50) NOT NULL,
   		EMP_PHONE INT,
   		EMP_SALARY INT,
   		EMP_EMAIL VARCHAR2(50) NOT NULL,
   		EMP_DOB DATE
    )
    CREATE TABLE USER_INFORMATION (
		  ID                   INT              NOT NULL,
		  USER_COUNTRY          VARCHAR2(255),
		  FIRST_NAME            VARCHAR2(255),
		  USER_GENDER           VARCHAR2(255),
		  LAST_NAME             VARCHAR2(255),
		  USER_PHONE            VARCHAR2(255),
		  USER_STATE            VARCHAR2(255),
		  USER_EMAIL            VARCHAR2(255),
		  USER_NAME             VARCHAR2(255),
		  USER_PASSWORD         VARCHAR2(255),
		  EMAIL_VALIDATION_KEY  VARCHAR2(255),
		  TOKEN_GENERATED_TIME  DATE
	)

GRANT SELECT,UPDATE,INSERT,DELETE ON COUNTRIES_LIST TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON INDIAN_STATES TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON EMPLOYEE TO PUBLIC
GRANT SELECT,UPDATE,INSERT,DELETE ON USER_INFORMATION TO PUBLIC;