/* Country Information */
INSERT INTO VINODH.COUNTRIES_LIST VALUES (1, 'IN', 'India');
INSERT INTO VINODH.COUNTRIES_LIST VALUES (2, 'US', 'America');

/* State Information*/
Insert into VINODH.INDIAN_STATES (STATE_ID, STATE_NAME) Values (1, 'ANDAMAN AND NICOBAR ISLANDS');
Insert into VINODH.INDIAN_STATES (STATE_ID, STATE_NAME) Values (2, 'ANDHRA PRADESH');