/* Country Information */
INSERT INTO VINODH.COUNTRIES_LIST VALUES (1, 'IN', 'India');
INSERT INTO VINODH.COUNTRIES_LIST VALUES (2, 'US', 'America');

/* State Information*/
Insert into VINODH.INDIAN_STATES (STATE_ID, STATE_NAME) Values (1, 'ANDAMAN AND NICOBAR ISLANDS');
Insert into VINODH.INDIAN_STATES (STATE_ID, STATE_NAME) Values (2, 'ANDHRA PRADESH');
Insert into VINODH.INDIAN_STATES (STATE_ID, STATE_NAME) Values (3, 'ANDHRA VINODH');

/* User Information */
Insert into VINODH.USER_INFORMATION (ID,USER_COUNTRY,FIRST_NAME,USER_GENDER,LAST_NAME,USER_PHONE,USER_STATE,USER_EMAIL,USER_NAME,USER_PASSWORD,EMAIL_VALIDATION_KEY,TOKEN_GENERATED_TIME)
VALUES (100,'India','Vinodh Kumar','Male','Thimmisetty','7894561303','Andhra Pradesh','vinodh5052@gmail.com','Vinodh5052','1212121313','12345678',SYSDATE);
Insert into VINODH.USER_INFORMATION (ID,USER_COUNTRY,FIRST_NAME,USER_GENDER,LAST_NAME,USER_PHONE,USER_STATE,USER_EMAIL,USER_NAME,USER_PASSWORD,EMAIL_VALIDATION_KEY,TOKEN_GENERATED_TIME)
VALUES (200,'India','Vinodh Kumar','Male','Thimmi','7894561303','Andhra Pradesh','vinodh1234@gmail.com','Vinodh1234','1212121313','12345678',SYSDATE);
Insert into VINODH.USER_INFORMATION (ID,USER_COUNTRY,FIRST_NAME,USER_GENDER,LAST_NAME,USER_PHONE,USER_STATE,USER_EMAIL,USER_NAME,USER_PASSWORD,EMAIL_VALIDATION_KEY,TOKEN_GENERATED_TIME)
VALUES (300,'India','Pavan Kumar','Male','Ventrapati','7894561303','Andhra Pradesh','pavan5052@gmail.com','Pavan5052','1212121313','12345678',SYSDATE);
Insert into VINODH.USER_INFORMATION (ID,USER_COUNTRY,FIRST_NAME,USER_GENDER,LAST_NAME,USER_PHONE,USER_STATE,USER_EMAIL,USER_NAME,USER_PASSWORD,EMAIL_VALIDATION_KEY,TOKEN_GENERATED_TIME)
VALUES (400,'India','Pavan Kumar','Male','Ventrapati','7894561303','Andhra Pradesh','pavan1234@gmail.com','Pavan1234','1212121313','12345678',SYSDATE);
Insert into VINODH.USER_INFORMATION (ID,USER_COUNTRY,FIRST_NAME,USER_GENDER,LAST_NAME,USER_PHONE,USER_STATE,USER_EMAIL,USER_NAME,USER_PASSWORD,EMAIL_VALIDATION_KEY,TOKEN_GENERATED_TIME)
VALUES (500,'India','Vadan','Male','Puli','7894561303','Andhra Pradesh','vadan123@gmail.com','Vadan1234','1212121313','12345678',SYSDATE);


/* Authentication*/
INSERT INTO VINODH.AUTHENTICATION_USER_DETAILS (USER_ID,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_PHONE,USER_ROLE,APPLICATION_NAME,LAST_MODIFIED_BY,LAST_MODIFIED_DATE)
VALUES(100,'Vinodh Kumar','Thimmisetty','test@gmail.com',7894561230,'SUPER_ADMIN','spring-security','Vinodh',SYSDATE);

INSERT INTO VINODH.AUTHENTICATION_USER_DETAILS (USER_ID,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_PHONE,USER_ROLE,APPLICATION_NAME,LAST_MODIFIED_BY,LAST_MODIFIED_DATE)
VALUES(200,'Vinodh Kumar','Thimmisetty','test@gmail.com',7894561230,'APPLICATION_ADMIN','spring-security','Vinodh',SYSDATE);

INSERT INTO VINODH.AUTHENTICATION_USER_DETAILS (USER_ID,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_PHONE,USER_ROLE,APPLICATION_NAME,LAST_MODIFIED_BY,LAST_MODIFIED_DATE)
VALUES(300,'Vinodh Kumar','Thimmisetty','test@gmail.com',7894561230,'APPLICATION_USER','spring-security','Vinodh',SYSDATE);

INSERT INTO VINODH.AUTHENTICATION_USER_DETAILS (USER_ID,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_PHONE,USER_ROLE,APPLICATION_NAME,LAST_MODIFIED_BY,LAST_MODIFIED_DATE)
VALUES(400,'Vinodh Kumar','Thimmisetty','test@gmail.com',7894561230,'OTHER','spring-security','Vinodh',SYSDATE);
 